name: feast
description: "A new Flutter project."
publish_to: 'none'
version: 1.5.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  awesome_dialog: ^3.2.1
  cached_network_image: ^3.4.1
  firebase_auth: ^5.3.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  flutter_bloc: ^8.1.5
  flutter_offline: ^3.0.1
  gap: ^3.0.1
  google_sign_in: ^6.2.1
  rive: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
